 
export const CHANGEEMAIL='CHANGEEMAIL';
export const CHANGEPASSWORD='CHANGEPASSWORD';
export const CHANGESTATUSLOGIN = 'CHANGESTATUSLOGIN';
export const CHANGESEARCHSTAFF = 'CHANGESEARCHSTAFF';
export const CHANGESEARCHPROJECTUSER = 'CHANGESEARCHPROJECTUSER';
export const CHECKPASSWORDCURRENT = 'CHECKPASSWORDCURRENT';
export const CHANGEPASSAFLOG = 'CHANGEPASSAFLOG';
export const CHECKPASSCONFIRM = 'CHECKPASSCONFIRM';
export const GETTOKEN = 'GETTOKEN';
export const GETUID = 'GETUID';
export const GETCLIENT = 'GETCLIENT';
export const EMAILSEND = 'EMAILSEND';
export const GETPASSRESET = 'GETPASSRESET';
export const GETPASSRESETCONF = 'GETPASSRESETCONF';
